/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace com.coveo.blitz.thrift
{
  /// <summary>
  /// Les types de documents qui peuvent etre retournes par l'Indexer
  /// </summary>
  public enum DocumentType
  {
    /// <summary>
    /// Signifie qu'un document contient des informations sur un artiste.
    /// </summary>
    ARTIST = 1,
    /// <summary>
    /// Signifie qu'un document contient des informations sur un album.
    /// </summary>
    ALBUM = 2,
  }
}
