/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace com.coveo.blitz.thrift
{
  /// <summary>
  /// Les type de noeud dans l'arbre syntaxique de la requete.
  /// </summary>
  public enum NodeType
  {
    /// <summary>
    /// Un noeud qui represente un operateur de requete (AND, OR, ...)
    /// "value" contient l'operateur.
    /// "leftPart" contient la partie a droite de l'operateur.
    /// "rightPart" contient la partie de gauche de l'operateur.
    /// </summary>
    OPERATOR = 1,
    /// <summary>
    /// Un noeud qui represente un terme de la requete ("Madonna", "Justin", "Hello World")
    /// "value" contient le terme.
    /// "leftPart" est null.
    /// "rightPart" est null.
    /// </summary>
    LITERAL = 2,
  }
}
